name: vetcalc_db
services:
  postgres:
    image: docker.io/library/postgres:15.3
    environment:
      POSTGRES_DB: "${VCDB_DB}"
      POSTGRES_USER: "${VCDB_USER}"
      POSTGRES_PASSWORD: "${VCDB_PASSWORD}"
    ports:
      - "${VCDB_PORT}:5432"
    networks:
      back-tier:
        aliases:
          - database
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  back-tier:

