name: vetcalc_db
services:
  postgres:
    image: docker.io/library/postgres:15.3
    environment:
      POSTGRES_DB: vcdb
      POSTGRES_USER: postgres
    env_file: ./db.env
    ports:
      - "33333:5432"
    networks:
      back-tier:
        aliases:
          - database
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  back-tier:

